### PR TITLE
JS and CSS update - meal discount

### PR DESCRIPTION
**Pull request by casserole27**
Added function, logic, and styling to add a discount to Your Order when there are two or more items.

### CODE REVIEW

**Comment by casserole27** [comment]
I ALMOST have this finished. I just have to figure out why it's removing the discount after using the "remove all" buttons if I have a quantity greater than 1.
I know it has something to do with this:

```javascript
  if(updateIndex > -1) { //if the item is already in the array increase its quantity
            cartArray[updateIndex].quantity += 1;
 ```

**Comment by Rapidisimo** [comment]
Hmm I tried replicating the issue but I wasn't able to. Can you give me a step by step or record something for me if you would like for me to check it out.

Thanks

**Comment by casserole27** [comment]
@Rapidisimo Do we want the discount to work when it's only two different types of items, or just two items in general? In the screenshot, more than one quantity of pizza does not yield a discount. Currently, the discount only works for two different types of items. 

ROA-discount
ROA-discount-2

**Comment by Rapidisimo** [comment]
Yeah the way you have it setup right now (array length) it means a discount is applied when buying two different types of items.
If you wanted to apply a discount when you buy more of one item then you have to make a loop to go through each item in the cartArray and count their quantities.
The items don't appear more than once because that's how we kept it from adding several lines of "Pizza" and instead just increment their quantity.
It's your choice, what type of discount you want to implement.
I also think it would be helpful to let the user know there is a discount before they they make their choice.

**Pull request merged**
